### ISSUE TITLE
Reference in Dalliance (not export) shifts when clicking Export button

### ISSUE THREAD

**Issue by dlrice** [dasmoth/dalliance#133]
I've noticed that the reference can shift when getting ready to export an image (though the exported image looks good). I suspect this is related to #132

Browser: Firefox

1. Load http://www.biodalliance.org/datasets/bodymap-skeletal_muscle-chr22.bam as a binary file.
2. Visit 22:29,999,581
3. Zoom in all the way
![image](https://cloud.githubusercontent.com/assets/4357962/5644963/642a7122-9661-11e4-8237-2019b269ddca.png)
4. Notice that the edge of the reads finish at 22:29,999,578
5. Click print/export icon
6. Select image
7. Visit 22:29,999,611
![image](https://cloud.githubusercontent.com/assets/4357962/5644969/7094002c-9661-11e4-8f04-9edfb256c274.png)
8. Click export button
![image](https://cloud.githubusercontent.com/assets/4357962/5644978/781a9d88-9661-11e4-887f-b8ee412ea58b.png)

You should now see that the reference has shifted so that 22:29,999,581 is at the centre of the screen while the reads haven't followed (a noticeable difference is that the reads now finish at  22:29,999,548). This shift is also retained when closing the export menu. The export does look lined up properly though.
![image](https://cloud.githubusercontent.com/assets/4357962/5644992/b3fda17e-9661-11e4-8b71-8c9e6c202c0a.png)

**Comment by dasmoth** [comment]
Thanks very much for reporting this.  As you say, it's related to a not-quite-correct fix for #132.  Should be okay now.
