### ISSUE TITLE
Can't zoom in after zooming out

### ISSUE THREAD

**Issue by ryan-williams** [dasmoth/dalliance#144]
Ported from [cycledash #547](https://github.com/hammerlab/cycledash/issues/547).

I open a 50bp window:

![](https://s3.amazonaws.com/f.cl.ly/items/253J3z2D231e2j0I2j0t/Screen%20Shot%202015-03-17%20at%202.53.09%20PM.png)

I zoom out:

![](https://s3.amazonaws.com/f.cl.ly/items/310I0i04210s293o3l0E/Screen%20Shot%202015-03-17%20at%202.53.42%20PM.png)

At this point, clicking "zoom in" seems to no-op, which is confusing.

**Comment by ryan-williams** [comment]
1. it would be nice if zooming in/out was "undo"able in some sense.
2. failing that, disabling each zoom button when it won't have an effect would help.

thanks!

**Comment by dasmoth** [comment]
1) Absolutely agree re: undoability.  Actually, I think all UI actions in the browser should be undoable, but it's probably a little way off.

2) Good idea, I'll do that.

**Comment by dasmoth** [comment]
Buttons are now disabled when you can't zoom further.

Undo is still on the agenda for a future version.
