### ISSUE TITLE
Workaround / better error message for "Bumping limit exceeded"

### ISSUE THREAD

**Issue by ryan-williams** [dasmoth/dalliance#145]
Ported from [cycledash #546](https://github.com/hammerlab/cycledash/issues/546)

I see that error message frequently, don't know what it means, and don't know what if anything I can do to fix/work around it.

![](https://s3.amazonaws.com/f.cl.ly/items/3b3s1e2g1A230c070F3z/Screen%20Shot%202015-03-17%20at%202.40.28%20PM.png)

**Comment by ymen** [comment]
cc @dasmoth 

From what I understand, the "bumping limit" is a limit on the number of "rows" that the track is allowed to display. I think this was just to prevent the unlikely case that a BAM file has too many alignments and the browser crash when trying to render all of them. But when you see this error message, there are **features in the BAM track that aren't rendered**, which can be quite problematic!

In terms of getting around the problems:

The newer version has an option in the track editor, which can be used to configure this interactively. (ref https://github.com/dasmoth/dalliance/issues/65#issuecomment-49027714)

Before
![screenshot 2015-03-18 at 9 11 27 am](https://cloud.githubusercontent.com/assets/7988161/6713334/d85a4a3a-cd4e-11e4-9be2-7e4232b30c47.png)

After changing to bump limit to **1000**
![screenshot 2015-03-18 at 9 12 17 am](https://cloud.githubusercontent.com/assets/7988161/6713351/ef381ad4-cd4e-11e4-867c-e72e56b5229e.png)

From experience though, I usually just set `subtierMax` property when adding a track programmatically to a really large number, or overwrite the default `subtierMax` [here](https://github.com/dasmoth/dalliance/blob/cd516a69a8aee575f87a9911cd80d7a681b374c9/js/cbrowser.js#L88) (ref https://github.com/dasmoth/dalliance/issues/65#issuecomment-47210549)

Hope this helps, Thomas can correct me if I'm wrong :)

**Comment by dasmoth** [comment]
Thanks @ymen, that's all correct.  I'll just mention that the "Bump overlaps" option in the track editor is simply a UI for setting `subtierMax`.

**Comment by keithcallenberg** [comment]
@ymen called the situation in which this would occur "unlikely", but imagine that you are displaying targeted sequencing data and regularly have 2000x coverage? In this context, it is not practical to increase the subtierMax high enough that this warning/error message goes away; if we want to visualize individual reads, we must be happy with downsampling. Is there any way we could either expose a config parameter to disable this "Bumping limit" message, or make it somehow less obtrusive (it covers the top 1-2 reads). I am not well versed in js, but if I was able to make that change, do you think it could be merged @dasmoth?

For reference, IGV downsamples reads by default and does not tell the user (http://www.broadinstitute.org/igv/Preferences#Alignments).
