### ISSUE TITLE
DAS Registry is outdated

### ISSUE THREAD

**Issue by Traksewt** [dasmoth/dalliance#160]
Dalliance tries to hit the DAS Registry, e.g.:
http://www.dasregistry.org/das/sources?organism=9606&authority=GRCh&version=37

However, in chrome it gives the error: No 'Access-Control-Allow-Origin' header is present on the requested resource. The bigger problem is that it appears dasregistry.org is no longer functional, as this message appears on the site on all pages:

The www.dasregistry.org website is no longer supported at The Wellcome Trust Sanger Institute.

If there is no current alternative, should this be disabled?

**Comment by dasmoth** [comment]
Should already be done in 0.13.4 and master.  See 7e450f03937604a13f9f494a2c0c703f9a64746c
