### ISSUE TITLE
Feature Request: Interactions

### ISSUE THREAD

**Issue by HAShihab** [dasmoth/dalliance#162]
Would it be possible to add a way of representing genomic interactions in Biodalliance, e.g. something similar to the arcs connecting two loci in the WashU browser (see Figure 1b in http://www.nature.com/nmeth/journal/v10/n5/full/nmeth.2440.html).

Edit: could this be an extension to Issue #151?

**Comment by dasmoth** [comment]
Yes, it would be great to have something like this.  Let's track progress over at #151.
