### ISSUE TITLE
Change Genome colors

### ISSUE THREAD

**Issue by wookoouk** [dasmoth/dalliance#177]
Is there any way to change the colors used in the reference track ?
They dont really fit with the rest of the site at the moment.

![dalliance_color copy](https://cloud.githubusercontent.com/assets/445964/9550267/314cb94c-4da2-11e5-9005-20932bb575c5.png)

**Comment by dasmoth** [comment]
Yes.  Try something like:

new Browser({
   baseColors: {
            'A': 'purple',
            'C': 'yellow',
            // ...
   }
});

For reference, the defaults are at:

https://github.com/dasmoth/dalliance/blob/master/js/cbrowser.js#L151-L157

**Comment by wookoouk** [comment]
awesome, cheers
