### ISSUE TITLE
bed file

### ISSUE THREAD

**Issue by thomasyu888** [dasmoth/dalliance#181]
Hello,

Thanks in advance for your time.  I was wondering if I was doing something wrong configuring the bed file.  This is my source configuration: 
```
{name: 'example_bed',
collapseSuperGroups:true,
uri: 'http://localhost/example.bed.gz',
tier_type: 'tabix',
payload: 'BED'}
```
This is the bed file I bgzipped and created a tabix index file on it.
>chr7    127471196  127472363 
>chr7    127472363  127473530 
>chr7    127473530  127474697 
>chr7    127474697  127475864
>chr7    127475864  127477031 
>chr7    127477031  127478198 
>chr7    127478198  127479365
>chr7    127479365  127480532
>chr7    127480532  127481699 

Please kindly let me know what I'm doing wrong. 

Tom

**Comment by dasmoth** [comment]
The "payload" names are case sensitive.  Could you try:

            payload: 'bed'

instead.

Will leave this open until I have a chance to look into an error-handling issue this reveals...

**Comment by thomasyu888** [comment]
Thank you for your help.  I changed the payload to lowercase, but it still doesn't seem to want to display anything.  Attached is a screenshot.  
![biodalliance_bed](https://cloud.githubusercontent.com/assets/10556275/9863712/3dbff574-5af7-11e5-83cc-3c66232f9351.png)

**Comment by ajo2995** [comment]
Try another chromosome. I am seeing a bit g where the first contig ( I my case ) is not working for tabix indexed bed files
Andrew

**Comment by dasmoth** [comment]
@ajo2995 that sounds as though some lines from your file have been interpreted as header data when making the Tabix index.  Do you have a file I could try?

**Comment by dasmoth** [comment]
Okay, found a bug which quite likely explains this and also @ajo2995's problem.  Solution implemented on the 'master' branch (although not currently in the release).

Do re-open if you're still having problems.

**Comment by ajo2995** [comment]
That fixed it. Thanks!

**Comment by thomasyu888** [comment]
Thank you for your help.  This seems to work if I have a bed file that includes all the chromosomes.  However, when I just put the above bed file in, it seems to only plot the first line.

![screen shot 2015-09-16 at 11 23 18 am](https://cloud.githubusercontent.com/assets/10556275/9914901/f6e3fa38-5c68-11e5-8a96-e48746970ef9.png)

**Comment by dasmoth** [comment]
That's very odd and doesn't match the results of my own testing using the file you sent.  Any chance you could send me your .bed.gz and tabix files for that (via offline e-mail probably best).
