### ISSUE TITLE
BioDalliance won't work properly in chrome browser, works fine in firefox..

### ISSUE THREAD

**Issue by serine** [dasmoth/dalliance#190]
Hi Thomas, 

I'm having issues with latest BioDalliance and chrome browser. No track being displayed, first image below. However if I press any of the buttons on the top, right hand side all tracks appear and work fine - second image. There is no error in console at that time. I don't have this issue in firefox though... 

```
[biostation]:~% google-chrome --version
Google Chrome 49.0.2623.87 
````
```
[biostation]:~% firefox --version
Mozilla Firefox 45.0
```
Here is the [link to BioDalliacne](http://bioinformatics.erc.monash.edu/home/kirill/test/check.html)

If I start zooming in/out, then I see this error repeats

```
GET http://bioinformatics.erc.monash.edu/home/kirill/test/testDataFiles/standard_sorted.bam net::ERR_TUNNEL_CONNECTION_FAILED
```

Looks like there is something wrong in fetching the file, however I can see reads in the browser.

![dalliancechrom1](https://cloud.githubusercontent.com/assets/6700099/14193274/2481ac0c-f7ef-11e5-9e02-f8f7d4ee7d98.png)
![dalliancechrom2](https://cloud.githubusercontent.com/assets/6700099/14193275/24abc5b4-f7ef-11e5-9aa6-c8dc0c8d9d35.png)

Steps that I took to compile dalliance from source

- `git clone dalliance`

```
[biostation]:~% node --version
v4.4.1
[biostation]:~% npm --version
2.14.20
```
- `npm install` 
- `./node_modules/gulp/bin/gulp.js` 
- then I took `dallinace-all.js` file from build directory

Thanks,

**Comment by serine** [comment]
Also tried using `dalliance-compiled.js` from biodalliance.org same issue.. 

```
wget http://www.biodalliance.org/release-0.13/dalliance-compiled.js
```

Although can use BioDalliance browse through chrome at biodalliance.org..

**Comment by dasmoth** [comment]
Hi Kirill, sorry to hear you're having trouble.

I can't think of an immediate reason why Biodalliance should be doing this.  In particular, the ERR_TUNNEL_CONNECTION_FAILED errors are new to me, and what I've been able to find seems to relate pretty specifically to proxy servers.  

Is your Chrome instance configured to use a proxy?  If so, does Firefox use the same configuration?

**Comment by serine** [comment]
Hi Thomas, 

No, I don't have any proxy set up ( I haven't set anything up). When I go to check proxy settings in chrome I get this message

```
When running Google Chrome under a supported desktop environment, the system proxy settings will be used. However, either your system is not supported or there was a problem launching your system configuration.

But you can still configure via the command line. Please see man google-chrome-stable for more information on flags and environment variables.
```
However I dont think this is the main problem. I only get this error if I'm selecting BAM file. Once I select the bam file and try zoom in/out I get that error. 

I tried accessing this instance of biodalliance from home and I don't seem to get this error so you are most likely right about some proxy set up at my work... But the problem is this instance of biodalliance doesn't render any of the tracks.. In this instance I have three tracks 1. Annotation 2. Reference genome 3. standard (which is BAM file)

The only way for me to get those track displayed is if I press any of the buttons on the top right hand side...

I'm using linux ubuntu 14.04 however my colleague using Mac OS and he is also unable to visualise this instance of biodalliance in chrome.

Where you able to visualise and use this instance of biodalliance ? 

Thanks

**Comment by dasmoth** [comment]
Okay, was focussed more on the BAM-related issue.

Yes, I see what you mean about the tracks not showing until you open one of the extra UI panes.

What happens if you temporarily remove the "fullScreen: true" from the config?  What if you include some other content on the page, either above or below the browser element?

**Comment by serine** [comment]
I tried all of those suggestions. I left them in place. None of them seems to be helping.. As an aside I previously used dalliance compiled from source and it worked fine.. I'll try to find that old js file, I might have deleted it.. 
One other thing when I refresh I can briefly see all tracks being rendered and then disappear

Thanks

**Comment by dasmoth** [comment]
What happens if you build from the0.13.x branch?

**Comment by serine** [comment]
I did, same thing..link is updated.. very strange..I will try to play around with different chrome versions.. I Also tried hosting off different server just in case, [here is that same page off different url](http://115.146.85.14/kirill/test/check.html) 

Thanks

**Comment by dasmoth** [comment]
Hi again Kirill,

I think I've solved this: I can reproduce the "invisible tracks" problem using an HTML file similar to yours.  However, if I change the first line from:
               
                 <!DOCTYPE>

...to the standard HTML5:

                <!DOCTYPE html>

All is well.  I assume that the unusual DOCTYPE declaration is triggering Chrome's quirks mode, although exactly how that leads to hidden tracks, I'm still not entirely sure...

Anyway, hopefully you'll be able to fix yours by changing the DOCTYPE line -- let me know if that causes trouble.

**Comment by serine** [comment]
Hi Thomas, 

really sorry to take up your time for this... I can confirm that that fixed the problem.. 

Thanks so much for your help
