### ISSUE TITLE
Change default Vertical guideline to Right

### ISSUE THREAD

**Issue by mdphan** [dasmoth/dalliance#199]
Hi,

Could you please show me how to change the default Vertical guideline from 'Center' to 'Right'?

Many thanks,

mdphan

**Comment by dasmoth** [comment]
Hi.

You should be able to do this with:

        new Browser({
                rulerLocation: 'right'
                // other opts...
        });

I've just spotted one minor bug: if you've *already* run the Biodalliance instance in a given browser, it won't pick up different a rulerLocation specified in this manner.  I'll fix this soon, but a simple workaround is to provide a new value for the 'cookieKey' configuration parameter (which means that any stale configuration data in localStorage will be ignored).

**Comment by mdphan** [comment]
Thanks for your prompt reply. If you have time maybe include this option in the webpage 'http://www.biodalliance.org/config.html' as well.

All the best.

**Comment by dasmoth** [comment]
Good point -- done.
