### ISSUE TITLE
Does Dalliance supprt uncompressed BED files ?

### ISSUE THREAD

**Issue by max-l** [dasmoth/dalliance#206]
I have bigbed files that work, but when I try to produce uncompressed bed files, I get : 

     Uncaught RangeError: byte length of Int16Array should be a multiple of 2
    at new Int16Array (native)

The bed file contains this single line : 

      1	3845	13620	ENSDART00000152276	500	+	3845	13620	0,153,0	8	85,164,25,114,147,92,121,548	0,800,1332,1687,2401,5204,5394,9227

Do I need to give it a mime type ?

**Comment by dasmoth** [comment]
Textual BED files should be an option, but they need a somewhat different config from bigBeds.  E.g.:

         {name: "MyFeatures",
          uri: "http://server/myfile.bed",
          tier_type: 'memstore',
          payload: 'bed'}

See http://www.biodalliance.org/config-source.html for more details.

**Comment by max-l** [comment]
Thanks @dasmoth  I get this error with my single line BED file : 

     Exception TypeError: Cannot read property 'timeout' of undefined

I load it like this : 

       [
            {name: 'Genome',
             twoBitURI: assembly.assemblyUrl + '/complete-genome.2bit',
             stylesheet_uri: 'https://www.biodalliance.org/stylesheets/gencode.xml',
             tier_type: 'sequence'
            },
            {name: "MyFeatures",
             uri: '/api/1/lab/altorf/singleBed/psm/213803.bed',
             tier_type: 'memstore',
             stylesheet_uri: 'https://www.biodalliance.org/stylesheets/gencode.xml',
              payload: 'bed',
              collapseSuperGroups: true
            }
          ]

**Comment by dasmoth** [comment]
Bother, seems to be an unfixed issue in 0.13.7.  Building your own from git should be fine, or try http://www.biodalliance.org/dev/dalliance-compiled.js

**Comment by dasmoth** [comment]
Have also pushed out 0.13.8 which includes the fix for this.

**Comment by max-l** [comment]
@dasmoth  where can I get the 0.13.8 version ? I notice that this project does not use GIT tags.
I notice that my code is broken in the 0.14 release (https://www.biodalliance.org/release-0.14/dalliance-compiled.js).    I will have to hunt down what is the latest commitID under which my code works, 
(I suppose that will be in the 0.13.x branch) but I think that GIT tags would really be helpful for building and debugging specific versions.

**Comment by max-l** [comment]
ok, I found it : https://github.com/dasmoth/dalliance/commits/0.13.x
so to find a particular release, you go in the branch and look for commits that have "version bump" in their description, then in the DIFF, you look at the actual version change.

**Comment by dasmoth** [comment]
No, there haven't been git tags for individual releases (although there have been branches for major releases).  I'll try adding tags for releases in the future.

There isn't yet a v0.14.0 final released.  However, there probably ought to be, and I'm generally recommending using git master at this point.  You can compile itself (checkout, npm install, run gulp).  Or there's a reasonably up-to-date version at https://www.biodalliance.org/dev/dalliance-compiled.js.

If you're still having problems with the master branch, do let me know what's amiss and I'll see if I can help track it down.
