### ISSUE TITLE
How to disable error messages on empty bed files 

### ISSUE THREAD

**Issue by max-l** [dasmoth/dalliance#207]
Hi, I have an application that fetches tracks, sometimes the bed file will be empty,
The browser shows this message : "Error fetching data: No data; see browser console"
it would be nice to be able to inhibit the message.

**Comment by dasmoth** [comment]
Sorry, was unintentionally being a bit strict about this case.  Fixed now in master.

**Comment by max-l** [comment]
Thanks !
