### ISSUE TITLE
uncompresed (memstore) BED parser have a faulty +1 at the end of segments

### ISSUE THREAD

**Issue by max-l** [dasmoth/dalliance#223]
I load a compressed BED (.bb), the exons display correctly
if I load the same bed uncompressed, the exons have a length of + 1 

the uncompressed track is loaded with : 

              {name: "my bed track",
               uri: xyz.bed',
               tier_type: 'memstore',
                stylesheet_uri: "https://www.biodalliance.org/stylesheets/gencode.xml",
                payload: 'bed',
                collapseSuperGroups: true
              }

**Comment by dasmoth** [comment]
Fixed by #224
