### ISSUE TITLE
Define bump overlaps limit in JSON-type style

### ISSUE THREAD

**Issue by moritzschaefer** [dasmoth/dalliance#229]
Neither in the XML nor in the JSON style guide, I found an option to set the "bump overlaps limit" (see picture). Is there a way to set this programatically and if yes, how?

![image](https://user-images.githubusercontent.com/2714540/35820719-cad02874-0aa6-11e8-936f-464a4055aece.png)

**Comment by dasmoth** [comment]
Try `subtierMax` in your track configuration(s).

**Comment by moritzschaefer** [comment]
Thank you.
