### ISSUE TITLE
bigbed tracks show the features twice

### ISSUE THREAD

**Issue by benwbooth** [dasmoth/dalliance#244]
I noticed in the latest dalliance master, when using bigBed as a track source file, all of the features in the bigbed track are displayed twice. If I load the earlier stable dalliance, I don't see this issue. I think this issue must have come up recently. It doesn't seem to matter which bigBed file I use, they all list the features twice.

**Comment by dasmoth** [comment]
Thanks, will investigate...

**Comment by dasmoth** [comment]
Thanks very much for reporting this.  I've not been able to find anything specific in the bigBed support that could explain this issue.  However, if your bigBed files all contain gene or "gene-like" data (i.e. "bed12" format with exon coordinates etc.), I think I've spotted a rendering bug which might explain what you're seeing.  I've fixed the render (which should now match 0.13 behaviour).

Could you give this a try?

**Comment by benwbooth** [comment]
Yes that fixes the issue. Thanks!
